### ISSUE TITLE
Grayscale support for B/W panels?

### ISSUE THREAD

**Issue by thedevleon** [avsaase/weact-studio-epd#12]
Any idea if the B/W ePaper screens could support grayscale?

I have a Waveshare 2.9 B/W v2 board here that only works with the `WeActStudio290BlackWhiteDriver` but not the actual [epd_waveshare](https://docs.rs/epd-waveshare/latest/epd_waveshare/index.html)::[epd2in13_v2](https://docs.rs/epd-waveshare/latest/epd_waveshare/epd2in13_v2/index.html#) driver, which makes me think that maybe the WeAct 2.9 B/W and WaveShare 2.9 B/W share the same panel (at least in the screen I have here).

Waveshare says [their V2 board supports grayscale](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_Manual), so does that mean the WeAct V2 might too if they're the same panel or controller IC?

pixelcolor::Gray4 could be used?

**Comment by thedevleon** [comment]
The FPC connector has "FPC-7519 rev.b" printed on it, which based on [this](https://github.com/todd-herbert/heltec-eink-modules?tab=readme-ov-file#29-inch) seems to be a DEPG0290BS. AFAIK the WeAct 2.9 B/W s also a variant of DEPG0290BS.

**Comment by avsaase** [comment]
Good question! I have no idea to be honest. None of the product images of the WeActStudio displays that I've seen show use of grayscale. It's also not demonstrated in their [examples](https://github.com/WeActStudio/WeActStudio.EpaperModule/tree/master/Example), although that could also be explained by a lack of support in GxEPD2 driver that they use. If it is really the same driver IC and panel as the Waveshare display then it's perhaps it possible to get grayscale to work. Currently I have no need for this feature though and I'm busy with another project so I won't be able to investigate this further right now. If you figure it out I'm happy to take a PR.

**Comment by thedevleon** [comment]
After digging a bit more in the datasheets and in the code, it seems that (at least the 2.9 B/W one) does not support grayscale. I also have the 1.54 and 4.2 inch on order, maybe they are different. Will reopen the issue if I find something.

**Comment by wariuccio** [comment]
According to https://github.com/ZinggJM/GxEPD2/discussions/97 some of the WeAct studio displays support grayscale.
I haven’t had a chance to try it out yet but that discussion is encouraging
